import { GlassCard } from "@/components/ui/GlassCard";

const features = [
  {
    title: "0G Compute inference",
    body: "Every reply is generated by 0G Compute. No OpenAI or Gemini fallback path — ever."
  },
  {
    title: "0G Storage memory",
    body: "Client data, chat history, and daily summaries live encrypted on 0G testnet Storage."
  },
  {
    title: "Client operations",
    body: "List, get, create, update, and summarize — six fixed tools, nothing more."
  },
  {
    title: "Telegram interface",
    body: "One shared bot. Multiple chats can bind to the same demo workspace."
  }
];

export function Features() {
  return (
    <section id="features" className="px-6 py-20">
      <div className="mx-auto max-w-6xl">
        <h2 className="mb-3 text-3xl font-semibold tracking-tight md:text-4xl">Features</h2>
        <p className="mb-12 max-w-2xl text-white/65">
          Tightly scoped. Nothing more than what the demo needs.
        </p>
        <div className="grid gap-4 md:grid-cols-2">
          {features.map((f) => (
            <GlassCard key={f.title}>
              <div className="mb-2 text-lg font-medium">{f.title}</div>
              <div className="text-sm text-white/65">{f.body}</div>
            </GlassCard>
          ))}
        </div>
      </div>
    </section>
  );
}
